domain   = 'drlm.org'

nodes = [
  load 'conf/boxes_to_test.rb' 
]

# Deployment of the testing enviroment

Vagrant.configure("2") do |config|

  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.boot_timeout = 480
      nodeconfig.vm.box = node[:box]
      nodeconfig.vm.hostname = node[:hostname] + ".box"
      # Disable Shared Folders, we're not using them.
      nodeconfig.vm.synced_folder ".", "/vagrant", :disabled => true
      nodeconfig.vm.network :forwarded_port, guest: 22, host: node[:fport], id: 'ssh'
      nodeconfig.vm.network "private_network", ip: node[:ip], :mac => node[:mac], :name => node[:net], :adapter => node[:nic]

      if !(node[:ip2].nil?) || !(node[:net2].nil?) || !(node[:nic2].nil?)
        nodeconfig.vm.network "private_network", ip: node[:ip2], :mac => node[:mac2], :name => node[:net2], :adapter => node[:nic2]
      end

      memory = node[:ram] ? node[:ram] : 256;
      nodeconfig.vm.provider :virtualbox do |vb|
       	vb.name = node[:hostname]
       	vb.gui = false
        vb.customize [
          "modifyvm", :id,
          "--cpuexecutioncap", "50",
          "--memory", memory.to_s,
       	  "--usb", "off",
       	  "--usbehci", "off",
       	  "--cableconnected1", "on",
        ]
      end
    end
  end

  nodes.each do |node|
       	config.vm.define node[:hostname] do |nodeconfig|
       	  nodeconfig.vm.provision "shell", path: node[:script]
       	end
  end
end
